// Transform Ventures, editable content model.
// DEFAULTS mirror the current hardcoded home page exactly, so the public
// site looks identical even before anything is edited (and if the DB is empty).
// SCHEMA drives the admin panel's form generation.

const DEFAULTS = {
  home: {
    site: {
      logo: "assets/transform-ventures-white.png",
    },
    hero: {
      titleLine1: "Build with",
      titleLine2: "conviction",
      lead: 'Capital, resources, and strategic guidance for blockchain and digital asset projects with high-growth potential. Led by Michael Terpin, the "Godfather of Crypto."',
      cta1Text: "Explore divisions →",
      cta1Href: "pages/divisions.html",
      cta2Text: "Get in touch",
      cta2Href: "pages/contact.html",
      twitter: "#",
      linkedin: "https://www.linkedin.com/company/transform-ventures/",
      youtube: "#",
    },
    divisionsHead: {
      eyebrow: "Our ecosystem",
      title: "Five divisions. One vision.",
      sub: "Transform Ventures operates across five specialized divisions, from digital asset PR and blockchain events to venture capital, strategic advisory, and a bitcoin-only hedge fund.",
    },
    divisions: [
      { name: "Transform Group", tag: "Communications & PR", desc: "The original blockchain PR firm, launched the first-ever token sale (Mastercoin, 2013) and powered 100+ prominent ICO-era launches including Ethereum, EOS, Augur, and Tether.", kpi: "100+ ICO launches · Since 2013" },
      { name: "Transform Events", tag: "Tokenize · BitAngels · Tiger Mansion", desc: "Premier blockchain events connecting founders and investors worldwide through curated gatherings.", kpi: "3 flagship events" },
      { name: "Transform Capital", tag: "Family Office", desc: "Strategic investments across the digital asset landscape with a long-term investment horizon.", kpi: "Multi-strategy" },
      { name: "Transform Strategies", tag: "Advisory & Consulting", desc: "Go-to-market strategy, tokenomics design, and ecosystem development for blockchain ventures.", kpi: "Seed → Scale" },
      { name: "Bitcoin Supercycle Fund", tag: "BTC Investment Fund", desc: 'The first liquid bitcoin-only hedge fund using the "Four Seasons of Bitcoin" cycle model and algorithmic trading.', kpi: "100% BTC · Algo" },
    ],
    feature: {
      tag1: "Advisory",
      tag2: "Strategy",
      title: "Every digital asset venture finds its path.",
      desc: "Decades of combined experience in token launch strategy, digital asset go-to-market, tokenomics design, and investor relations, helping blockchain ventures succeed from seed to scale.",
      bullet1: "End-to-end advisory on token design, distribution, and launch",
      bullet2: "Strategic positioning and market-entry plans",
      bullet3: "Access to the full Transform Ventures network",
      cta1Text: "Start a conversation →",
      cta1Href: "pages/contact.html",
      cta2Text: "Learn more",
      cta2Href: "pages/divisions.html",
    },
    statBand: {
      cap: "Portfolio & track record",
      bignum: "$200M",
      capDesc: "Globe Newswire exit to NASDAQ, the foundation that seeded 12+ years of digital asset ventures, clients, and capital.",
      sub1n: "100+",
      sub1l: "ICO-era token launches",
      sub2n: "2013",
      sub2l: "Launched first-ever token sale",
    },
    eventsHead: {
      eyebrow: "Transform Events",
      title: "Where the industry connects.",
      sub: "Flagship blockchain conferences and digital asset networking events bringing together industry leaders, angel investors, and founders.",
    },
    events: [
      { name: "Tokenize", tag: "Global Conference", desc: "Industry leaders, investors, and innovators exploring the future of tokenization.", img: "assets/tokenize-vegas.jpg", url: "https://tokenizeconference.com/" },
      { name: "BitAngels", tag: "Since 2013 · Angel Network", desc: "The world's first angel investor network for digital currency startups.", img: "assets/bitangels-group.webp", url: "https://bitangels.network/" },
      { name: "Tiger Mansion", tag: "Invite Only", desc: "An exclusive, invite-only gathering for top-tier digital asset investors and founders.", img: "assets/tigermansion-event.jpg", url: "https://www.tigermansionlv.com/" },
    ],
    fund: {
      eyebrow: "Investment Fund",
      title: "Bitcoin Supercycle Fund.",
      sub: 'The first liquid bitcoin-only hedge fund combining the "Four Seasons of Bitcoin" cycle model with algorithmic trading.',
      bookImg: "assets/bitcoin-supercycle-book.jpg",
      badge: "Amazon Best Seller · 2024",
      bookTitle: "Bitcoin Supercycle",
      bookDesc: "How the crypto calendar can make you rich, by Michael Terpin. The foundational thesis behind the fund's seasonal signal and cycle-driven strategy.",
      kpi1n: "100%", kpi1l: "Bitcoin-Only",
      kpi2n: "Algo", kpi2l: "Algorithmic Trading",
      kpi3n: "4 Seasons", kpi3l: "Cycle-driven",
      cta1Text: "Learn more →",
      cta1Href: "pages/division-fund.html",
      cta2Text: "Buy on Amazon ↗",
      cta2Href: "https://www.amazon.com/Bitcoin-Supercycle-Crypto-Calendar-Make/dp/151078215X",
    },
    leader: {
      eyebrow: "Leadership",
      title: "Meet the founder.",
      sub: "Three decades of building at the intersection of media, technology, and capital, from Globe Newswire to the Bitcoin Supercycle Fund.",
      photoImg: "assets/michael-terpin.jpg",
      quote: '"Godfather of Crypto"',
      source: "CNBC",
      role: "Founder & CEO · CIO, Bitcoin Supercycle Fund",
      name: "Michael Terpin",
      para1: 'Early bitcoin investor, thought leader, and serial entrepreneur, known as the "Godfather of Crypto" (CNBC). Chief Investment Officer of the Bitcoin Supercycle Fund and author of Bitcoin Supercycle (Skyhorse Publishing, 2024), which correctly predicted the November 2024 all-time high for bitcoin.',
      para2: "Co-founder of BitAngels (2013), the first digital asset angel group, and creator of Tokenize, the leading conference series connecting investors with blockchain. Previously founded Globe Newswire, the first internet-based newswire, sold to NASDAQ for $200M.",
      stat1n: "100+", stat1l: "ICO-era launches",
      stat2n: "$200M", stat2l: "Globe Newswire exit",
      stat3n: "2013", stat3l: "First digital asset angel group",
      tags: ["Godfather of Crypto", "BitAngels Co-Founder", "Tokenize Creator", "Author", "Puerto Rico"],
      ctaText: "Full bio →",
      ctaHref: "pages/leadership.html",
    },
    faqHead: {
      eyebrow: "FAQ",
      title: "Frequently asked questions.",
      sub: "Quick answers about Transform Ventures, Michael Terpin, and the Bitcoin Supercycle Fund.",
    },
    faq: [
      { q: "What is Transform Ventures?", a: "Transform Ventures is the blockchain and digital asset venture platform of Michael Terpin, known as the \"Godfather of Crypto.\" It provides capital, resources, and strategic guidance to high-growth digital asset projects across five specialized divisions, and is headquartered in San Juan, Puerto Rico." },
      { q: "Who is Michael Terpin?", a: "Michael Terpin is the founder and CEO of Transform Ventures and an early bitcoin investor known as the \"Godfather of Crypto\" (CNBC). He founded Transform Group (the original blockchain PR firm), co-founded BitAngels (the first digital asset angel group, 2013), created the Tokenize conference, and authored Bitcoin Supercycle (2024). He previously founded Globe Newswire, sold to NASDAQ for $200M." },
      { q: "What is the Bitcoin Supercycle Fund?", a: "The Bitcoin Supercycle Fund is the first liquid bitcoin-only hedge fund. It combines Michael Terpin's \"Four Seasons of Bitcoin\" cycle model with algorithmic trading and season-specific strategies, using institutional-grade infrastructure (Coinbase Prime custody, NAV Fund Services administration)." },
      { q: "What are the five divisions of Transform Ventures?", a: "Transform Group (communications & PR), Transform Events (Tokenize, BitAngels, Tiger Mansion), Transform Capital (family office), Transform Strategies (advisory & consulting), and the Bitcoin Supercycle Fund (a bitcoin-only hedge fund)." },
      { q: "Where is Transform Ventures located?", a: "Transform Ventures is headquartered in San Juan, Puerto Rico." },
      { q: "How can I contact Transform Ventures?", a: "Email info@transformventures.io or use the contact page. Transform Ventures works with projects on investments, advisory, events, and partnerships." },
    ],
    finalCta: {
      title: "Ready to transform your blockchain venture?",
      desc: "Whether you're raising capital, launching a token, or need strategic guidance, let's connect.",
      cta1Text: "Start a conversation →",
      cta1Href: "pages/contact.html",
      cta2Text: "Latest news & media",
      cta2Href: "pages/media.html",
    },
    footer: {
      blurb: "Capital, resources, and strategic guidance for blockchain and digital asset projects with high-growth potential.",
      copyright: "© 2026 Transform Ventures. All rights reserved.",
      location: "San Juan, Puerto Rico",
    },
  },
};

// Schema: drives the admin editor. type: text | textarea | image | url | list
const SCHEMA = {
  home: {
    label: "Home Page",
    sections: [
      { key: "site", label: "Site / Branding", fields: [
        { key: "logo", label: "Logo (nav + footer)", type: "image" },
      ]},
      { key: "hero", label: "Hero", fields: [
        { key: "titleLine1", label: "Headline: line 1", type: "text" },
        { key: "titleLine2", label: "Headline: line 2", type: "text" },
        { key: "lead", label: "Lead paragraph", type: "textarea" },
        { key: "cta1Text", label: "Button 1: text", type: "text" },
        { key: "cta1Href", label: "Button 1: link", type: "url" },
        { key: "cta2Text", label: "Button 2: text", type: "text" },
        { key: "cta2Href", label: "Button 2: link", type: "url" },
        { key: "twitter", label: "Twitter / X link", type: "url" },
        { key: "linkedin", label: "LinkedIn link", type: "url" },
        { key: "youtube", label: "YouTube link", type: "url" },
      ]},
      { key: "divisionsHead", label: "Divisions: heading", fields: [
        { key: "eyebrow", label: "Eyebrow", type: "text" },
        { key: "title", label: "Title", type: "text" },
        { key: "sub", label: "Subtitle", type: "textarea" },
      ]},
      { key: "divisions", label: "Divisions: cards", type: "list", itemLabel: "name", fields: [
        { key: "name", label: "Name", type: "text" },
        { key: "tag", label: "Tag", type: "text" },
        { key: "desc", label: "Description", type: "textarea" },
        { key: "kpi", label: "KPI line", type: "text" },
      ]},
      { key: "feature", label: "Feature / Advisory", fields: [
        { key: "tag1", label: "Pill 1", type: "text" },
        { key: "tag2", label: "Pill 2", type: "text" },
        { key: "title", label: "Title", type: "text" },
        { key: "desc", label: "Description", type: "textarea" },
        { key: "bullet1", label: "Bullet 1", type: "text" },
        { key: "bullet2", label: "Bullet 2", type: "text" },
        { key: "bullet3", label: "Bullet 3", type: "text" },
        { key: "cta1Text", label: "Button 1: text", type: "text" },
        { key: "cta1Href", label: "Button 1: link", type: "url" },
        { key: "cta2Text", label: "Button 2: text", type: "text" },
        { key: "cta2Href", label: "Button 2: link", type: "url" },
      ]},
      { key: "statBand", label: "Stat band", fields: [
        { key: "cap", label: "Caption", type: "text" },
        { key: "bignum", label: "Big number", type: "text" },
        { key: "capDesc", label: "Description", type: "textarea" },
        { key: "sub1n", label: "Sub-stat 1: number", type: "text" },
        { key: "sub1l", label: "Sub-stat 1: label", type: "text" },
        { key: "sub2n", label: "Sub-stat 2: number", type: "text" },
        { key: "sub2l", label: "Sub-stat 2: label", type: "text" },
      ]},
      { key: "eventsHead", label: "Events: heading", fields: [
        { key: "eyebrow", label: "Eyebrow", type: "text" },
        { key: "title", label: "Title", type: "text" },
        { key: "sub", label: "Subtitle", type: "textarea" },
      ]},
      { key: "events", label: "Events: cards", type: "list", itemLabel: "name", fields: [
        { key: "name", label: "Name", type: "text" },
        { key: "tag", label: "Tag", type: "text" },
        { key: "desc", label: "Description", type: "textarea" },
        { key: "img", label: "Image", type: "image" },
        { key: "url", label: "Link", type: "url" },
      ]},
      { key: "fund", label: "Bitcoin Supercycle Fund", fields: [
        { key: "eyebrow", label: "Eyebrow", type: "text" },
        { key: "title", label: "Title", type: "text" },
        { key: "sub", label: "Subtitle", type: "textarea" },
        { key: "bookImg", label: "Book image", type: "image" },
        { key: "badge", label: "Badge", type: "text" },
        { key: "bookTitle", label: "Book title", type: "text" },
        { key: "bookDesc", label: "Book description", type: "textarea" },
        { key: "kpi1n", label: "KPI 1: number", type: "text" },
        { key: "kpi1l", label: "KPI 1: label", type: "text" },
        { key: "kpi2n", label: "KPI 2: number", type: "text" },
        { key: "kpi2l", label: "KPI 2: label", type: "text" },
        { key: "kpi3n", label: "KPI 3: number", type: "text" },
        { key: "kpi3l", label: "KPI 3: label", type: "text" },
        { key: "cta1Text", label: "Button 1: text", type: "text" },
        { key: "cta1Href", label: "Button 1: link", type: "url" },
        { key: "cta2Text", label: "Button 2: text", type: "text" },
        { key: "cta2Href", label: "Button 2: link", type: "url" },
      ]},
      { key: "leader", label: "Leadership", fields: [
        { key: "eyebrow", label: "Eyebrow", type: "text" },
        { key: "title", label: "Title", type: "text" },
        { key: "sub", label: "Subtitle", type: "textarea" },
        { key: "photoImg", label: "Photo", type: "image" },
        { key: "quote", label: "Photo caption: quote", type: "text" },
        { key: "source", label: "Photo caption: source", type: "text" },
        { key: "role", label: "Role", type: "text" },
        { key: "name", label: "Name", type: "text" },
        { key: "para1", label: "Bio paragraph 1", type: "textarea" },
        { key: "para2", label: "Bio paragraph 2", type: "textarea" },
        { key: "stat1n", label: "Stat 1: number", type: "text" },
        { key: "stat1l", label: "Stat 1: label", type: "text" },
        { key: "stat2n", label: "Stat 2: number", type: "text" },
        { key: "stat2l", label: "Stat 2: label", type: "text" },
        { key: "stat3n", label: "Stat 3: number", type: "text" },
        { key: "stat3l", label: "Stat 3: label", type: "text" },
        { key: "tags", label: "Tags (one per line)", type: "lines" },
        { key: "ctaText", label: "Button: text", type: "text" },
        { key: "ctaHref", label: "Button: link", type: "url" },
      ]},
      { key: "faqHead", label: "FAQ: heading", fields: [
        { key: "eyebrow", label: "Eyebrow", type: "text" },
        { key: "title", label: "Title", type: "text" },
        { key: "sub", label: "Subtitle", type: "textarea" },
      ]},
      { key: "faq", label: "FAQ: questions", type: "list", itemLabel: "q", fields: [
        { key: "q", label: "Question", type: "text" },
        { key: "a", label: "Answer", type: "textarea" },
      ]},
      { key: "finalCta", label: "Final call-to-action", fields: [
        { key: "title", label: "Title", type: "text" },
        { key: "desc", label: "Description", type: "textarea" },
        { key: "cta1Text", label: "Button 1: text", type: "text" },
        { key: "cta1Href", label: "Button 1: link", type: "url" },
        { key: "cta2Text", label: "Button 2: text", type: "text" },
        { key: "cta2Href", label: "Button 2: link", type: "url" },
      ]},
      { key: "footer", label: "Footer", fields: [
        { key: "blurb", label: "Blurb", type: "textarea" },
        { key: "copyright", label: "Copyright line", type: "text" },
        { key: "location", label: "Location", type: "text" },
      ]},
    ],
  },
};

// Merge in the subpage content models.
const sub = require("./content-subpages");
Object.assign(DEFAULTS, sub.DEFAULTS);
Object.assign(SCHEMA, sub.SCHEMA);

module.exports = { DEFAULTS, SCHEMA };
